apiVersion: v1
kind: Service
metadata:
  name: {{ include "xds-cp-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xds-cp-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "xds-cp-operator.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: metrics
  selector:
    {{- include "xds-cp-operator.selectorLabels" . | nindent 4 }} 