# This rule is not used by the project xds-cp-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the xds.okassov.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: xds-cp-operator
    app.kubernetes.io/managed-by: kustomize
  name: xdscontrolplane-editor-role
rules:
- apiGroups:
  - xds.okassov
  resources:
  - xdscontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xds.okassov
  resources:
  - xdscontrolplanes/status
  verbs:
  - get
