apiVersion: xds.okassov/v1alpha1
kind: XDSControlPlane
metadata:
  labels:
    app.kubernetes.io/name: xds-cp-operator
    app.kubernetes.io/managed-by: kustomize
  name: xdscontrolplane-sample
spec:
  # TODO(user): Add fields here
